#!/bin/bash

# Set the project directory
PROJECT_DIR="/home/tlindell/WORK/QT_LIBRARY_WATCHER"

# Patterns to search for CMake artifacts
CMAKE_FILES=("CMakeLists.txt" "CMakeCache.txt")
CMAKE_DIRS=("CMakeFiles" "build-cmake" "cmake-build-debug" "cmake-build-release")

echo "🚀 Starting CMake cleanup in $PROJECT_DIR..."

# Remove CMake-related files
for file in "${CMAKE_FILES[@]}"; do
    find "$PROJECT_DIR" -name "$file" -type f -exec rm -v {} +
done

# Remove CMake-related directories
for dir in "${CMAKE_DIRS[@]}"; do
    find "$PROJECT_DIR" -name "$dir" -type d -exec rm -rfv {} +
done

# Optionally, clean any Makefiles generated by CMake
find "$PROJECT_DIR" -name "Makefile" -exec grep -l "CMake" {} \; -exec rm -v {} +

echo "✅ CMake cleanup completed successfully!"
